import type { Metadata } from "next";
// import localFont from "next/font/local";
import { Inter as Epilogue } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { BackgroundBeamsWithCollision } from "@/components/ui/background-beams-with-collision";
import { FloatingNav } from "@/components/ui/floating-navbar";
import { IconHome, IconMessage, IconUser } from "@tabler/icons-react";

const fontEpilogue = Epilogue({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navItems = [
    {
      name: "Home",
      link: "/",
      icon: <IconHome className="h-4 w-4 text-neutral-500 dark:text-white" />,
    },
    {
      name: "About",
      link: "/about",
      icon: <IconUser className="h-4 w-4 text-neutral-500 dark:text-white" />,
    },
    {
      name: "Contact",
      link: "/contact",
      icon: (
        <IconMessage className="h-4 w-4 text-neutral-500 dark:text-white" />
      ),
    },
  ];
  return (
    <html lang="en">
      <body className={cn("", fontEpilogue.className)}>
        <BackgroundBeamsWithCollision className="fixed md:h-screen to-white inset-0 -z-10">
          <div></div>
        </BackgroundBeamsWithCollision>
        <FloatingNav navItems={navItems} />
        {children}
      </body>
    </html>
  );
}
